name: Deploy .NET no Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Trilha-Esporte
    env:
      IMAGE_NAME: "us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dotnet-repo/trilha-esporte:v1.0-${{ github.sha }}"

    steps:
      # 游댳 Checkout do c칩digo
      - name: Checkout do c칩digo
        uses: actions/checkout@v4

      # 游댳 Autenticar no Google Cloud
      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 游댳 Configurar autentica칞칚o do Docker para o Artifact Registry
      - name: Configurar autentica칞칚o do Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # 游댳 Verificar a vers칚o do Docker e se buildx est치 instalado
      - name: Verificar a vers칚o do Docker
        run: |
          docker --version
          docker buildx version || echo "docker buildx n칚o est치 instalado"

      # 游댳 Garantir que estamos usando o build tradicional (docker build)
      - name: For칞ar uso do docker build (sem buildx)
        run: |
          docker build --version || echo "docker build n칚o est치 instalado"

      # 游댳 Construir a imagem Docker
      - name: Construir a imagem Docker
        run: |
          echo "Construindo a imagem Docker..."
          docker build -t ${IMAGE_NAME} .

      # 游댳 Enviar a imagem para o Google Artifact Registry
      - name: Enviar imagem para o Google Artifact Registry
        run: |
          echo "Enviando a imagem para o Google Artifact Registry..."
          docker push ${IMAGE_NAME}

      # 游댳 Fazer o deploy no Cloud Run
      - name: Deploy no Cloud Run
        run: |
          echo "Realizando deploy no Cloud Run..."
          gcloud run deploy trilha-esporte \
            --image=${IMAGE_NAME} \
            --region=us-central1 \
            --platform=managed \
            --port=8080 \
            --allow-unauthenticated \
            --timeout=2000s \
            --set-env-vars="DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT }},DB_NAME=${{ secrets.DB_NAME }}"

      # 游댳 Mostrar URL do servi칞o
      - name: Exibir URL do servi칞o
        run: |
          echo "Obtendo
