name: Deploy .NET no Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Trilha-Esporte
    env:
      IMAGE_NAME: "us-central1-docker.pkg.dev/${{secrets.GCP_PROJECT_ID }}/dotnet-repo/trilha-esporte:v1.0-${{github.sha }}"

    steps:
      # 🔹 Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 🔹 Autenticar no Google Cloud
      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 🔹 Configurar autenticação do Docker para o Artifact Registry
      - name: Configurar autenticação do Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # 🔹 Configurar Buildx para multi-arch
      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v3

      - name: Desabilitar o Buildx (caso esteja ativado)
        run: |
          docker buildx use default

      - name: Construir a imagem Docker
        run: |
          echo "Construindo a imagem Docker..."
          docker build -t $IMAGE_NAME .



          echo "Enviando a imagem para o Google Artifact Registry..."
          docker push ${IMAGE_NAME}

      # 🔹 Fazer o deploy no Cloud Run
      - name: Deploy no Cloud Run
        run: |
          echo "Realizando deploy no Cloud Run..."
          gcloud run deploy trilha-esporte \
            --image=${IMAGE_NAME} \
            --region=us-central1 \
            --platform=managed \
            --port=8080 \
            --allow-unauthenticated \
            --timeout=2000s \
            --set-env-vars="DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT }},DB_NAME=${{ secrets.DB_NAME }}"

      # 🔹 Mostrar a URL do serviço
      - name: Exibir URL do serviço
        run: |
          echo "Obtendo a URL do serviço..."
          gcloud run services describe trilha-esporte --region=us-central1 --format 'value(status.url)'
