name: Deploy .NET no Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Trilha-Esporte
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurar Docker para Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Definir variável de nome da imagem
        id: vars
        run: |
          echo "IMAGE_NAME=us-central1-docker.pkg.dev/${GCP_PROJECT_ID}/dotnet-repo/trilha-esporte:${GITHUB_SHA}" >> $GITHUB_ENV
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build da imagem Docker
        run: |
          echo "Construindo a imagem Docker..."
          echo "Nome da imagem: $IMAGE_NAME"
          docker build -t $IMAGE_NAME .

      - name: Push da imagem para Artifact Registry
        run: |
          docker push $IMAGE_NAME

      - name: Deploy no Cloud Run
        run: |
          gcloud run deploy trilha-esporte \
            --image=$IMAGE_NAME \
            --region=us-central1 \
            --platform=managed \
            --port=8080 \
            --allow-unauthenticated \
            --timeout=2000s \
            --set-env-vars="DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT }},DB_NAME=${{ secrets.DB_NAME }}"

      - name: Mostrar URL do serviço
        run: |
          gcloud run services describe trilha-esporte \
            --region=us-central1 \
            --format='value(status.url)'
