name: Deploy .NET no Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Trilha-Esporte

    steps:
      # 🔹 Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 🔹 Autenticar no Google Cloud
      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 🔹 Configurar Docker para Artifact Registry
      - name: Configurar Docker para Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # 🔹 Configurar QEMU para multi-arch
      - name: Configurar QEMU para multi-arch
        uses: docker/setup-qemu-action@v3

      # 🔹 Configurar Buildx
      - name: Configurar Buildx
        uses: docker/setup-buildx-action@v3

      # 🔹 Definir nome da imagem Docker com nome padrão
      - name: Definir nome da imagem
        run: |
          IMAGE_NAME="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dotnet-repo/trilha-esporte:v1.0-${{ github.sha }}"
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV

      # 🔹 Construir a imagem Docker com Buildx
      - name: Construir a imagem Docker com Buildx
        run: |
          echo "Construindo a imagem Docker..."
          docker buildx build \
            --tag $IMAGE_NAME \
            --file Dockerfile \
            --progress plain \
            .

      # 🔹 Enviar a imagem para Artifact Registry
      - name: Enviar a imagem para Artifact Registry
        run: |
          echo "Enviando imagem para Artifact Registry..."
          docker push $IMAGE_NAME

      # 🔹 Realizar o deploy no Cloud Run
      - name: Deploy no Cloud Run
        run: |
          echo "Realizando deploy no Cloud Run..."
          gcloud run deploy trilha-esporte \
            --image=$IMAGE_NAME \
            --region=us-central1 \
            --platform=managed \
            --port=8080 \
            --allow-unauthenticated \
            --timeout=2000s \
            --set-env-vars="DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT }},DB_NAME=${{ secrets.DB_NAME }}"

      # 🔹 Exibir URL do serviço
      - name: Exibir URL do serviço
        run: |
          echo "URL do serviço:"
          gcloud run services describe trilha-esporte --region=us-central1 --format 'value(status.url)'
