name: Deploy .NET to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Trilha-Esporte
    env:
      IMAGE_NAME: "us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dotnet-repo/trilha-esporte:v1.0-${{ github.sha }}"

    steps:
      # 🔹 Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v4

      # 🔹 Autenticação no Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 🔹 Configurar Docker para o Artifact Registry
      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # 🔹 Debug: Mostrar o nome da imagem
      - name: Show Image Name
        run: |
          echo "IMAGE_NAME is: ${IMAGE_NAME}"
          if [ -z "${IMAGE_NAME}" ]; then
            echo "Error: IMAGE_NAME is not set!"
            exit 1
          fi

      # 🔹 Construção da Imagem Docker
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t ${IMAGE_NAME} .

      # 🔹 Push da imagem para o Artifact Registry
      - name: Push Docker image to Artifact Registry
        run: |
          echo "Pushing Docker image to Artifact Registry..."
          docker push ${IMAGE_NAME}

      # 🔹 Deploy para o Google Cloud Run
      - name: Deploy to Google Cloud Run
        run: |
          echo "Deploying to Google Cloud Run..."
          gcloud run deploy trilha-esporte \
            --image=${IMAGE_NAME} \
            --region=us-central1 \
            --platform=managed \
            --port=8080 \
            --allow-unauthenticated \
            --timeout=2000s \
            --set-env-vars="DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_HOST=${{ secrets.DB_HOST }},DB_PORT=${{ secrets.DB_PORT }},DB_NAME=${{ secrets.DB_NAME }}"

      # 🔹 Exibir URL do Serviço
      - name: Get URL of the Cloud Run service
        run: |
          echo "Fetching the URL of the service..."
          gcloud run services describe trilha-esporte \
            --region=us-central1 \
            --format 'value(status.url)'
